import = ["~/.config/alacritty/themes/everforest.toml"]

[bell]
animation = "EaseOutCubic"
color = "#282E3A"
duration = 1

[cursor]
blink_interval = 750
[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Fira Code"

[window]
opacity = 0.95

[window.padding]
x = 6
y = 6

[shell]
args = ["--login"]
program = "bash"
