#!/usr/bin/env bash

INTERVAL=3

icon () {
  if [[ "$1" == "no" ]]; then
    echo ""
  else
    echo ""
  fi
}

class () {
  if [[ "$1" == "no" ]]; then
    echo ""
  else
    echo "airplane-connected"
  fi

}

toggle () {
  if [[ "$1" == "no" ]]; then
    rfkill block all
    notify-send --urgency=normal -i airplane-mode-symbolic 'Airplane Mode' 'Airplane mode has been turned on'
  else
    rfkill unblock all
    notify-send --urgency=normal  -i airplane-mode-disabled-symbolic 'Airplane Mode' 'Airplane mode has been turned off'
  fi
}

main () {
  local status="$(rfkill list | sed -n 2p | awk '{print $3}')"
  if [[ "$1" == "toggle" ]]; then
    toggle $status
  else
    while true; do
      echo '{"'"icon"'":"'"$(icon $status)"'","'"class"'":"'"$(class $status)"'"}'
      sleep $INTERVAL;
    done
  fi
}

main "$*"
