#!/usr/bin/env bash

INTERVAL=3600

main () {
  declare updates="$(yay -Qua)"

  local color="#81A1C1"
  local num_updates_total=$(echo -e "${updates[*]}" | grep -vc '\[ignored\]')
  local num_updates_warn=$(echo -e "${updates[*]}" | grep -c '\(linux\|linux-lts\|linux-zen\)')

  if (( "$num_updates_warn" > 0 )); then
    color="#BF616A"
  elif (( "$num_updates_total" > 0 )); then
    color="#EBCB8B"
  fi

  jaq --null-input -r -c \
    --arg total "$num_updates_total" \
    --arg warn "$num_updates_warn" \
    --arg color "$color" \
    --arg version "$(uname -r)" \
    '{ "total": $total, "warn": $warn, "color": $color, "version": $version }'
}

while true; do
  main
  sleep $INTERVAL
done
