#!/usr/bin/env bash
INTERVAL=3600

main () {
  local updates=$(yay -Qua)
  local num_updates_total=$(echo $updates | wc -l)
  local num_updates_warn=$(echo $updates | grep -c '\(linux\|linux-lts\|linux-zen\)')

  echo '{"'"total"'":"'"$num_updates_total"'","'"warn"'":"'"$num_updates_warn"'","'"version"'":"'"$(uname -r)"'"}'
}

while true; do
  main
  sleep $INTERVAL
done
