#!/usr/bin/env bash
# see: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/linux/power_supply.h?h=v6.0.11

declare ICONS=('' '' '' '' '' '' '' '')
NUM_ICONS=$(bc <<< "100 / ${#ICONS[@]}")
INTERVAL=1
LOW_BAT_NOTIFY_INTERVAL=30

if [[ "$SYSTEM_THEME" == 'everforest' ]]; then
  RED='#e67e80'
	GREEN='#a7c080'
	YELLOW='#dbbc7f'
	BLUE='#7fbbb3'
else
 	RED='#BF616A'
	GREEN='#A3BE8C'
	YELLOW='#EBCB8B'
	BLUE='#B48EAD'
fi

geticon () {
  local level=$(awk -v n="$CAPACITY" -v c="$NUM_ICONS" 'BEGIN{print int(n/c-1)}')
	(( "$level" < 0 )) && {
		level=0
	}
	echo "${ICONS[$level]}"
}

status () {
	if [[ "$STATE" == "Charging" ]]; then
		echo -n "charging"

		if (( "$RATE" > 0 )); then
			echo ", $(gettime) left"
		else
			echo ""
		fi
	elif [[ "$STATE" == "Discharging" ]]; then
		echo "$(gettime)h left"
	else
		echo "fully charged"
	fi
}

color () {
	if [[ $(status) == charging* ]]; then
		if (($ALTERNATOR % 2 == 0)); then
			echo "$BLUE"
		else
			echo "$GREEN"
		fi
	else
		(( "$CAPACITY" <= 15 )) && {
			local n_seconds=$(date +%S)
			# Only notify once per LOW_BAT_NOTIFY_INTERVAL seconds
			(( "$n_seconds" % "$LOW_BAT_NOTIFY_INTERVAL" == 0 )) && {
				notify-send "Battery low: $CAPACITY%"
			}
		}
		if (( "$CAPACITY" <= 20 )); then
			echo "$RED"
		elif (( "$CAPACITY" <= 60 )); then
			echo "$YELLOW"
		else
			echo "$GREEN"
		fi
	fi
}

wattage () {
	local microwatts=1000000
	echo "$(bc -l <<< "scale=1; $RATE / $microwatts") W"
}

gettime () {
	local full=$(cat /sys/class/power_supply/BAT1/charge_full)
	local now=$(cat /sys/class/power_supply/BAT1/charge_now)

	if (( "$RATE" > 0 )); then
		if [[ "$STATE" == "Discharging" ]]; then
			EX="$now / $RATE"
		else
			EX="($full - $now) / $RATE"
		fi
		date -u -d@"$(bc -l <<< "$EX * 3600")" +%H:%M
	fi
}

ALTERNATOR=1
while true; do
	RATE=$(cat /sys/class/power_supply/BAT1/current_now)
	CAPACITY=$(cat /sys/class/power_supply/BAT1/capacity)
	STATE=$(cat /sys/class/power_supply/BAT1/status)

	echo '{ "icon": "'"$(geticon)"'", "percentage": '"$CAPACITY"', "wattage": "'"$(wattage)"'", "status": "'"$(status)"'", "color": "'"$(color)"'" }'
	sleep $INTERVAL
	((ALTERNATOR++))
done
