#!/usr/bin/env bash
# see: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/linux/power_supply.h?h=v6.0.11

icons=("" "" "" "" "" "" "" "")
num_icons=$(bc <<< "100 / ${#icons[@]}")


geticon () {
  local level=$(awk -v n="$CAPACITY" -v c="$num_icons" 'BEGIN{print int(n/c-1)}')
	if [[ "$level" -lt 0 ]]; then
		level=0
	fi
	echo "${icons[$level]}"
}

status () {
	if [ "$STATE" = "Charging" ]; then
		echo -n "charging"

		if [ "$RATE" -gt 0 ]; then
			echo ", $(gettime) left"
		else
			echo ""
		fi
	elif [ "$STATE" = "Discharging" ]; then
		echo "$(gettime)h left"
	else
		echo "fully charged"
	fi
}

color () {
	if [ "$CAPACITY" -le 20 ]; then
		echo '#f38ba8'
	else
		echo '#a6e3a1'
	fi
}

wattage () {
	local microwatts=1000000
	echo "$(bc -l <<< "scale=1; $RATE / $microwatts") W"
}

gettime () {
	local full=$(cat /sys/class/power_supply/BAT1/charge_full)
	local now=$(cat /sys/class/power_supply/BAT1/charge_now)

	if [ "$RATE" -gt 0 ]; then
		if [ "$STATE" = "Discharging" ]; then
			EX="$now / $RATE"
		else
			EX="($full - $now) / $RATE"
		fi
		date -u -d@"$(bc -l <<< "$EX * 3600")" +%H:%M
	fi
}

while true; do
	RATE=$(cat /sys/class/power_supply/BAT1/current_now)
	CAPACITY=$(cat /sys/class/power_supply/BAT1/capacity)
	STATE=$(cat /sys/class/power_supply/BAT1/status)

	echo '{ "icon": "'"$(geticon)"'", "percentage": '"$CAPACITY"', "wattage": "'"$(wattage)"'", "status": "'"$(status)"'", "color": "'"$(color)"'" }'
	sleep 3
done
