#!/usr/bin/env bash
SLEEP_INTERVAL=3

main () {
  local powered
  local status
  local name
  local battery

  if [[ "$1" == 'toggle' ]]; then
    rfkill toggle bluetooth
  else
    while true; do
      powered=$(bluetoothctl show | rg Powered | cut -f 2- -d ' ')
      status=$(bluetoothctl info)
      name=$(echo "$status" | rg Name | cut -f 2- -d ' ')

      if [[ "$(echo "$status" | rg Percentage)" != '' ]]; then
        battery="$(bluetoothctl info | grep Battery | sed -n 's/.*(\([0-9]*\)).*/\1/p')%"
      else
        battery=''
      fi

      if [[ "$powered" == 'yes' ]]; then
        if [[ "$status" != 'Missing device address argument'* ]]; then
          text="$name"
          icon=''
          class='active bt-connected'
        else
          icon=''
          text='Disconnected'
          class='inactive'
        fi
      else
        icon=''
        text='Bluetooth off'
        class='disabled'
      fi

      echo '{"icon":"'"$icon"'","battery":"'"$battery"'","text":"'"$text"'","class":"'"$class"'"}'

      sleep $SLEEP_INTERVAL
    done
  fi
}

main $*
