#!/usr/bin/env bash

declare icons=('' '' '')

get_level () {
  awk -v n="$(light)" 'BEGIN{print int(n/34)}'
}

# initial
main () {
  local icon=${icons[$(get_level)]}
  echo '{ "level": '"$(light)"', "icon": "'"$icon"'" }'

  udevadm monitor | rg --line-buffered 'backlight' | while read -r _; do
    icon="${icons[$(get_level)]}"

    echo '{ "level": '"$(light)"', "icon": "'"$icon"'" }'
  done
}

main
