#!/usr/bin/env bash
SLEEP_INTERVAL=5

main () {
  while true; do
    if ! systemctl is-active --quiet docker; then
        text='Docker not active'
        class='disabled'
    else
      local running="$(docker ps -q | wc -l)"
      local stopped="$(docker ps -q -f 'status=exited' | wc -l)"
      local created="$(docker ps -q -f 'status=created' | wc -l)"

      text="$running running, $stopped stopped, $created created"

      if [[ $running -gt 0 ]]; then
        class='active'
      else
        class='inactive'
      fi
    fi

    echo '{"icon":"'""'","text":"'"$text"'","class":"'"$class"'"}'

    sleep $SLEEP_INTERVAL
  done
}

main $*
