#!/usr/bin/env bash

INTERVAL=3
declare ICONS=(
  ''
  ''
  #''
  ''
  ''
  ''
)

main () {
  if [[ "$1" == "toggle" ]]; then
    rfkill toggle wlan
  else
    while true; do
      local status=$(nmcli g | tail -n 1 | awk '{print $1}')
      local signal=$(nmcli -f in-use,signal dev wifi | rg "\*" | awk '{ print $2 }')
      local essid=$(nmcli -t -f NAME connection show --active | head -n1 | sed 's/\"/\\"/g')
      local icon
      local level
      local color

      if [[ "$status" == 'disconnected' ]]; then
        icon='\ue1da'
        color='#ff5555'
        class=''
      else
        level=$(awk -v n="$signal" 'BEGIN{print int((n-1)/20)}')
        if (( "$level" > 4 )); then
          level=4
        fi

        icon=${ICONS[$level]}
        color='#f8f8f2'
        class='wifi-connected'
      fi

      echo '{"essid":"'"$essid"'","icon":"'"$icon"'","color":"'"$color"'","class":"'"$class"'"}'

      sleep $INTERVAL
    done
  fi
}

main "$*"
