#!/usr/bin/env node

const HACKER_NEWS_TOP_STORIES =
  'https://hacker-news.firebaseio.com/v0/topstories.json?orderBy="$priority"&limitToFirst=50'

function withHandledRejections(promises) {
  promises.forEach(p => {
    p.catch(() => {})
  })
  return promises
}

;(async function main() {
  const stories = []

  const topStoryIds = await (await fetch(HACKER_NEWS_TOP_STORIES)).json()

  const promises = topStoryIds.map(async id => {
    const response = await fetch(
      `https://hacker-news.firebaseio.com/v0/item/${id}.json`,
    )

    return response.json()
  })

  for await (const promise of withHandledRejections(promises)) {
    stories.push(promise)
  }

  console.log(JSON.stringify({ stories }))
})()
