#!/usr/bin/env bash

declare vol_icons=("" "" "")
SOURCE="SOURCE"
SINK="SINK"

get_vol () {
  local device="$1"
  local vol="$(wpctl get-volume @DEFAULT_AUDIO_$device@ | awk '{print int($2*100)}')"

  if (( "$vol" > 100 )); then
    echo 100
  else
    echo "$vol"
  fi
}

is_muted () {
  local device="$1"
  wpctl get-volume "@DEFAULT_AUDIO_$device"@ | rg -i muted
  echo $?
}

set_vol () {
  local device="$1"
  local volume="$2"
  wpctl set-volume "@DEFAULT_AUDIO_$device"@ "$(awk -v n="$volume" 'BEGIN{print (n / 100)}')"
}

set_mute () {
  local device="$1"
  wpctl set-mute "@DEFAULT_AUDIO_$device"@ toggle
}

is_invalid_src () {
  local src="$1"
  [[ "$src" != "$SOURCE" ]] && [[ "$src" != "$SINK" ]] && {
    echo 1
  }
}

panic () {
  local ec=$1; shift

  echo "[-] ERROR ($(current_time)): $*" >&2
  exit $ec
}

main () {
  local command="$1"
  local src="$2"
  local volume="$3"

  if [[ "$command" == "mute" ]]; then
    if [[ $(is_invalid_src "$src") ]]; then
      panic 1 "Can only mute $SINK or $SOURCE"
    fi

    set_mute "$src"
  elif [[ "$command" = "set_vol" ]]; then
    if [[ $(is_invalid_src "$src") ]]; then
      panic 1 "Can only set volume for $SINK or $SOURCE"
    elif (( "$volume" < 1 )) || (( "$volume" > 100 )); then
      panic 1 "Volume must be between 1 and 100"
    fi

    set_vol "$src" "$volume"
  else
    local lvl=$(awk -v n="$(get_vol "$SINK")" 'BEGIN{print int(n/34)}')

    if [[ "$(is_muted "$SINK")" == 1 ]]; then
      icon="${vol_icons[$lvl]}"
    else
      icon=""
    fi
    echo '{ "icon": "'"$icon"'", "percent": "'"$(get_vol "$SINK")"'", "microphone": "'"$(get_vol "$SOURCE")"'" }'

    # event loop
    pactl subscribe | rg --line-buffered "change" | while read -r _; do
      lvl=$(awk -v n="$(get_vol "$SINK")" 'BEGIN{print int(n/34)}')

      if [[ "$(is_muted "$SINK")" == 1 ]]; then
        icon="${vol_icons[$lvl]}"
      else
        icon=""
      fi

      echo '{ "icon": "'"$icon"'", "percent": "'"$(get_vol "$SINK")"'", "microphone": "'"$(get_vol "$SOURCE")"'" }'
    done
  fi
}

main "$*"
