#!/usr/bin/env bash

if [[ "$SYSTEM_THEME" == 'everforest' ]]; then
  #                   red       peach     green     blue
  declare -a colors=('#fc74b7' '#fab387' '#a6e3a1' '#e864ba')
  #                   pink      yellow    teal      lavender
  declare -a dimmed=('#9aa79d' '#f9e2af' '#94e2d5' '#94e2d5')
  empty='#272e33'
else
  #                   red       peach     green     blue
  declare -a colors=('#ff9dbe' '#fab387' '#a6e3a1' '#89b4fa')
  #                   pink      yellow    teal      lavender
  declare -a dimmed=('#f5c2d7' '#f9e2af' '#94e2d5' '#b4befe')
  empty='#313244'
fi


# get initial focused workspace
focusedws=$(i3-msg -t get_workspaces | gojq -r '.[] | select(.focused==true) | .name')

declare -A o=([1]=0 [2]=0 [3]=0 [4]=0 [5]=0 [6]=0 [7]=0 [8]=0 [9]=0 [10]=0)
declare -A monitormap
declare -A workspaces

# set color for each workspace
status () {
  if (( "${o[$1]}" == 1 )); then
    mon=${monitormap[${workspaces[$1]}]}

    if (( "$focusedws" == "$1" )); then
      echo -n "${colors[$mon]}"
    else
      echo -n "${dimmed[$mon]}"
    fi
  else
    echo -n "$empty"
  fi
}

# handle workspace create/destroy
workspace_event () {
  o[$1]=$2
  while read -r k v; do
    workspaces[$k]="$v";
  done < <(i3-msg -rt get_workspaces | gojq -r '.[]|"\(.name) \(.output)"')
}
# handle monitor (dis)connects
monitor_event () {
  while read -r k v; do
    monitormap["$k"]=$v;
  done < <(i3-msg -rt get_outputs | gojq -r '.[]|"\(.name) \(.id) "')
}

# get all apps titles in a workspace
applist () {
  local ws="$1"

  apps=$(hyprctl -j clients | gojq -jr '.[] | select(.workspace.id == '"$ws"') | .title + "\\n"')
  echo -En ${apps%"\n"}
}

# generate the json for eww
generate () {
  echo -n '['

  for i in {1..10}; do
    echo -n ''$([ $i -eq 1 ] || echo ,) '{ "number": "'"$i"'", "color": "'$(status "$i")'" }' #, "tooltip": "'$(applist "$i")'" }'
  done

  echo ']'
}

# setup

# add monitors
monitor_event

# add workspaces
while read -r k v; do
  workspaces[$k]="$v";
done < <(i3-msg -rt get_workspaces | gojq -r '.[]|"\(.name) \(.output)"')

# check occupied workspaces
for num in "${!workspaces[@]}"; do
  o[$num]=1
done
# generate initial widget
generate


# main loop
i3-msg -t subscribe '["workspace"]' --monitor | while read -r line; do
  change=$(echo "$line" |  gojq -r '(.change)')
  ws_id=$(echo "$line" |  gojq -r '(.current) | (.name)')

  case $change in
    'init')
      workspace_event "$ws_id" 1
    ;;

    'focus')
      focusedws="$ws_id"
    ;;

    'empty')
      workspace_event "$ws_id" 0
    ;;

  esac

  generate
done
