
[theme]
name = "/home/goldmund/.config/i3status-rs/themes/pink-nord.toml"

[icons] 
name= "awesome"

[icons.overrides]
cpu = "\uf2db"

[[block]]
block = "pacman"
interval = 600
format = "{pacman} + {aur} = {both} updates available"
format_singular = "{both} update available"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "yay -Qua"

[[block]]
block = "cpu"
interval = 1
format = "{barchart}"
info = 30
warning = 50
critical = 90

[[block]]
block = "backlight"
device = "intel_backlight"
invert_icons = true

[[block]]
block = "sound"
max_vol = 100
headphones_indicator = true

[[block]]
block = "battery"
interval = 10
format = "{percentage}"
warning = 30
critical = 15

[[block]]
block = "time"
interval = 6
format = "%l:%M %p"
