[colors.bright]
black = "0x31363b"
blue = "0x82abbc"
cyan = "0x89b482"
green = "0xacb765"
magenta = "0xb18a97"
red = "0xea5252"
white = "0xb3cfa7"
yellow = "0xc1bf89"

[colors.normal]
black = "0x212529"
blue = "0x82abbc"
cyan = "0x88b482"
green = "0xacb765"
magenta = "0xb18a97"
red = "0xea5252"
white = "0xb3cfa7"
yellow = "0xc1bf89"

[colors.primary]
background = "0x2d353b"
foreground = "0xffffff"
