idle_bg = "#282e3a"
idle_fg = "#F8F8F2"
info_bg = "#282e3a"
info_fg = "#F8F8F2"
good_bg = "#A3BE8C"
good_fg = "#282e3a"
warning_bg = "#EBCB8B"
warning_fg = "#F8F8F2"
critical_bg = "#BF616A"
critical_fg = "#F8F8F2"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "#282e3a"
 