FROM ubuntu:latest

RUN apt-get update && apt-get install -y git make vim bash curl socat jq stow i3

RUN sh -c "`curl -L https://raw.githubusercontent.com/rylnd/shpec/master/install.sh`"

WORKDIR /usr/app
COPY . .
