straps:
  - name: clib
    context: ~/repositories
    steps:
      - name: clone repo
        run: git clone --depth 1 https://github.com/exbotanical/clib-boilerplate .

      - name: cleanup old git
        run: rm -rf .git

      - name: interpolate placeholders
        run: |
          find . -type f -exec sed -i "s/<project>/${{ STRAP_PROJECT_NAME }}/g" {} \;
          sed -i "s/<year>/$(date +%Y)/" LICENSE

      - name: setup lib header
        run: |
          mv include/.gitkeep include/lib${{ STRAP_PROJECT_NAME }}.h

      - name: setup dirs
        run: mv _.github .github

      - name: setup git
        run: git init

  - name: cbin
    context: ~/repositories
    steps:
      - name: clone repo
        run: git clone --depth 1 https://github.com/exbotanical/cbin-boilerplate .

      - name: cleanup old git
        run: rm -rf .git

      - name: interpolate placeholders
        run: |
          find . -type f -exec sed -i "s/<project>/${{ STRAP_PROJECT_NAME }}/g" {} \;
          sed -i "s/<year>/$(date +%Y)/" LICENSE

      - name: setup dirs
        run: mv _.github .github

      - name: setup git
        run: git init

  - name: go
    context: ~/repositories
    steps:
      - name: clone repo
        run: git clone --depth 1 https://github.com/exbotanical/go-lib-boilerplate .

      - name: cleanup old git
        run: rm -rf .git

      - name: interpolate placeholders
        run: |
          find . -type f -exec sed -i "s/<project>/${{ STRAP_PROJECT_NAME }}/g" {} \;
          sed -i "s/<year>/$(date +%Y)/" LICENSE

      - name: setup git
        run: git init

  - name: typescript
    context: ~/repositories
    steps:
      - name: clone repo
        run: git clone --depth 1 https://github.com/exbotanical/ts-npm-boilerplate .

      - name: cleanup old git
        run: rm -rf .git

      - name: interpolate placeholders
        run: |
          find . -type f -exec sed -i "s/<project>/${{ STRAP_PROJECT_NAME }}/g" {} \;
          sed -i "s/<year>/$(date +%Y)/" LICENSE

      - name: setup git
        run: git init

      - name: install deps
        run: npm i

  - name: ocaml
    context: ~/repositories
    steps:
      - name: create switch
        run: opam switch create . && opam install ocaml-lsp-server ocamlformat
      - name: init dune project
        run: dune init proj ${{ STRAP_PROJECT_NAME }} .
